# Production Profile
spring.jpa.show-sql=false
logging.level.org.tampavolunteers=INFO
logging.level.org.springframework=WARN

# Disable Swagger UI in production
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false
